title: Karthik Mahalingam
email: karthik.mahalingam00@gmail.com
logo: assets/KarthikMahalingam.jpg
show_downloads: false
theme: jekyll-theme-minimal


links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/karthik-mahalingam/

