title: Karthik Mahalingam
email: kmahali2@asu.edu
logo: assets/Karthik_2.png
show_downloads: false
theme: jekyll-theme-chirpy


links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/karthik-mahalingam/

