title: Karthik Mahalingam
logo: assets/Karthik.jpeg
show_downloads: false
theme: jekyll-theme-minimal
email: karthik.mahalingam00@gmail.com

links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/karthik-mahalingam/

