title: Karthik Mahalingam
email: karthik.mahalingam00@gmail.com
logo: assets/Karthik_Mahalingam.png
show_downloads: false
theme: jekyll-theme-minimal


links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/karthik-mahalingam/

